name: loc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #firebase
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_ui_auth: ^1.12.1
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.2.17

  retrofit: ^4.0.3
  awesome_notifications: any
  flutter_bloc: ^8.1.3
  go_router: ^13.0.1
  equatable: ^2.0.5
  get_it: ^7.6.7
  dio: any
  liquid_pull_to_refresh: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.6
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
